---

# Configuration management

- name: Generate configuration
  become: True
  become_user: "{{ aptly_user }}"
  template:
    src: "{{ role_path }}/templates/aptly.conf.j2"
    dest: "{{ aptly_user_home }}/.aptly.conf"
    mode: '0700'

- name: System archive GPG keys management
  include: "{{ role_path }}/tasks/archive_gpg_keys.yml"

- name: Mirror management
  include: "{{ role_path }}/tasks/mirror_management.yml"

- name: Repo management
  include: "{{ role_path }}/tasks/repo_management.yml"

