---

# Repos management

- name: 'CONFIG | REPOS | List available repos'
  become: True
  become_user: "{{ aptly_user }}"
  become_method: "{{ aptly_become_method }}"
  command: 'aptly repo list -raw'
  changed_when: False
  register: 'aptly_repos_list'


- name: 'CONFIG | REPOS | Remove repos'
  become: True
  become_user: "{{ aptly_user }}"
  become_method: "{{ aptly_become_method }}"
  command: "aptly repo drop {{ item.name }}"
  register: 'aptly_repos_removed'
  notify: "HANDLER | Clean aptly database"
  with_items: "{{ aptly_repos }}"
  when:
    - "{{ item.state == 'absent' }}"
    - "{{ item.name in aptly_repos_list.stdout_lines }}"


- name: 'CONFIG | REPOS | Create repos'
  become: True
  become_user: "{{ aptly_user }}"
  become_method: "{{ aptly_become_method }}"
  command: >
    aptly repo create {{ item.create_flags | join(" ") }} {{ item.name }}
  register: 'aptly_repos_created'
  with_items: "{{ aptly_repos }}"
  when:
    - "{{ item.state == 'present' }}"
    - "{{ item.name not in aptly_repos_list.stdout_lines }}"
